#!/bin/bash


echo "deb http://ftp.us.debian.org/debian testing main" | sudo tee -a /etc/apt/sources.list

sudo apt-get update
sudo apt-get -t testing install -y python3.6

pip3 install polyswarm-api
