#!/usr/bin/env python
"""Regenerate the sync mirror from the canonical async source.

Reads ``src/polyswarm_api/aio/*.py`` (canonical async) and writes the
corresponding sync mirrors to ``src/polyswarm_api/*.py``. Run after any
change under ``src/polyswarm_api/aio/``; CI verifies the output is
current.

Skipped: ``aio/__init__.py`` (the public re-export shim, hand-written).
"""

import glob
import subprocess
import sys

import unasync


REPO_ROOT_SUBSTR = "/polyswarm_api/aio/"
OUTPUT_SUBSTR = "/polyswarm_api/"

# Source files under aio/ that should be unasync'd into the package root.
# __init__.py is excluded — it's a hand-written re-export.
SOURCES = sorted(
    p for p in glob.glob("src/polyswarm_api/aio/**/*.py", recursive=True)
    if not p.endswith("__init__.py")
)

# Generated files we will format with ruff after codegen.
GENERATED = [
    p.replace(REPO_ROOT_SUBSTR, OUTPUT_SUBSTR, 1) for p in SOURCES
]


REPLACEMENTS = {
    # Class-name swaps
    "PolySwarmAsyncAPI":     "PolyswarmAPI",
    "AsyncPolyswarmSession": "PolyswarmSession",
    # httpx types
    "AsyncClient":           "Client",
    "AsyncHTTPTransport":    "HTTPTransport",
    # typing helpers
    "AsyncGenerator":        "Iterator",
    "AsyncIterator":         "Iterator",
    "AsyncIterable":         "Iterable",
    # asyncio primitives mapped to their sync analogues
    "aclose":                "close",
    # httpx streaming-response read methods (used by the download path in
    # session.execute): the async transport iterates ``aiter_bytes`` and reads
    # error bodies with ``aread``; the sync transport uses ``iter_bytes`` /
    # ``read``.
    "aiter_bytes":           "iter_bytes",
    "aread":                 "read",
    # Rewrite `asyncio` → `time` at the identifier level.
    # ``import asyncio`` → ``import time``; ``asyncio.sleep(s)`` →
    # ``time.sleep(s)``. unasync tokenises before rewriting so string
    # literals (e.g. ``asyncio.gather`` in docstrings) are not touched.
    #
    # CONSTRAINT: ``asyncio.X`` for any ``X`` other than ``sleep`` will
    # produce ``time.X`` in the generated sync mirror, which is
    # nonsense. Don't introduce ``asyncio.gather`` / ``asyncio.Event``
    # / etc. on the canonical side without first restructuring this
    # rename (e.g. by importing ``sleep`` directly and renaming the
    # binding, or by inlining the asyncio-specific call inside a
    # ``# unasync: skip`` region — see the docs for unasync's escape
    # hatches).
    "asyncio":               "time",
    # imports inside the canonical async refer to polyswarm_api.aio.* —
    # rewrite that segment so the generated sync points at the root.
    "polyswarm_api.aio.":    "polyswarm_api.",
}


# ── Post-processing ────────────────────────────────────────────────
#
# unasync is a mechanical token-rewrite. The generated mirrors need only
# two content-agnostic fixups afterward: de-duplicating imports the
# rename map can introduce (e.g. ``asyncio`` -> ``time``) and prepending
# the "DO NOT EDIT" header. There are NO per-symbol behavioural patches —
# every method, including ``engines``, mirrors cleanly via unasync.


GENERATED_HEADER = (
    "# DO NOT EDIT — generated by scripts/regenerate_sync.py from\n"
    "# the canonical async source in polyswarm_api/aio/.\n"
    "# Edit aio/<file>.py then rerun the script.\n"
)


def add_generated_header(path: str) -> None:
    """Prepend a 'DO NOT EDIT' header to a generated file."""
    import pathlib
    target = pathlib.Path(path)
    text = target.read_text()
    if text.startswith("# DO NOT EDIT"):
        return
    target.write_text(GENERATED_HEADER + text)


def dedupe_imports(path: str) -> None:
    """Remove duplicate top-level imports introduced by the rename map.

    ``asyncio`` -> ``time`` produces an ``import time`` on the
    same file that may also have had an existing ``import time``.
    Drop the duplicate while preserving import order.
    """
    import pathlib
    target = pathlib.Path(path)
    lines = target.read_text().splitlines(keepends=True)
    seen = set()
    out = []
    for line in lines:
        stripped = line.rstrip()
        if stripped.startswith("import ") and not stripped.startswith("import ."):
            if stripped in seen:
                continue
            seen.add(stripped)
        out.append(line)
    target.write_text("".join(out))


def main() -> int:
    print("running unasync...")
    unasync.unasync_files(
        SOURCES,
        rules=[
            unasync.Rule(
                fromdir=REPO_ROOT_SUBSTR,
                todir=OUTPUT_SUBSTR,
                additional_replacements=REPLACEMENTS,
            ),
        ],
    )

    print("applying post-processing...")
    for path in GENERATED:
        dedupe_imports(path)
    for path in GENERATED:
        add_generated_header(path)

    print("formatting generated files with ruff...")
    cmd = ["ruff", "format", *GENERATED]
    result = subprocess.run(cmd)
    if result.returncode != 0:
        print("ruff format failed", file=sys.stderr)
        return result.returncode

    print("ok — sync mirror regenerated:")
    for path in GENERATED:
        print(f"  {path}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
