# DO NOT EDIT — generated by scripts/regenerate_sync.py from
# the canonical async source in polyswarm_api/aio/.
# Edit aio/<file>.py then rerun the script.
"""HTTP transport and request lifecycle.

The async version lives here; the sync mirror at
``polyswarm_api.core`` is generated by ``scripts/regenerate_sync.py``.
Transport-agnostic bases (``BaseJsonResource``, ``Hashable``,
``HttpxResponseAdapter``, helpers) live in ``polyswarm_api._bases`` —
shared by both sync and async cores so ``issubclass`` checks have a
single class identity.
"""

import json
import logging
from copy import deepcopy
from json.decoder import JSONDecodeError

import httpx

from polyswarm_api import settings, exceptions
from polyswarm_api._bases import (
    BaseJsonResource,
    HttpxResponseAdapter,
    RequestParamsEncoder,
    _normalise_bool_params,
)

# Re-export shared bases for backwards compatibility — callers that did
# ``from polyswarm_api.core import BaseJsonResource`` continue to work
# after the unasync split.
from polyswarm_api._bases import (  # noqa: F401
    BaseResource,
    Hashable,
    is_hex,
    is_valid_md5,
    is_valid_sha1,
    is_valid_sha256,
    parse_isoformat,
)

logger = logging.getLogger(__name__)


class PolyswarmSession:
    """Thin wrapper over the httpx client (sync or async, depending on
    which version of this module is loaded). Exposes the request /
    verify / headers surface that the corresponding request class
    expects.
    """

    def __init__(
        self,
        key,
        retries=settings.DEFAULT_RETRIES,
        user_agent=settings.DEFAULT_USER_AGENT,
        verify=True,
        timeout=settings.DEFAULT_HTTP_TIMEOUT,
        **httpx_kwargs,
    ):
        logger.debug("Creating AsyncPolyswarmSession (httpx-backed)")
        self.verify = verify
        hdrs = httpx_kwargs.pop("headers", None) or {}
        if key:
            hdrs["Authorization"] = key
        if user_agent:
            hdrs["User-Agent"] = user_agent
        transport = httpx_kwargs.pop("transport", None) or httpx.HTTPTransport(
            retries=retries,
            verify=verify,
        )
        self._client = httpx.Client(
            headers=hdrs,
            transport=transport,
            timeout=timeout,
            verify=verify,
            follow_redirects=True,
            **httpx_kwargs,
        )

    def request(self, method, url, **kwargs):
        # httpx doesn't accept ``stream=`` as a kwarg to ``.request()``;
        # downloads buffer fully into memory.
        kwargs.pop("stream", None)
        if "headers" in kwargs:
            kwargs["headers"] = {
                k: v for k, v in kwargs["headers"].items() if v is not None
            }
            if not kwargs["headers"]:
                del kwargs["headers"]
        if "params" in kwargs:
            kwargs["params"] = _normalise_bool_params(kwargs["params"])
        return self._client.request(method, url, **kwargs)

    @property
    def headers(self):
        return self._client.headers

    def close(self):
        self._client.close()


class PolyswarmRequest(object):
    """Holds a requests-compatible dict and the data needed to parse
    the response. The sync mirror generated by unasync is
    ``polyswarm_api.core.PolyswarmRequest``.
    """

    def __init__(
        self, api_instance, request_parameters, key=None, result_parser=None, **kwargs
    ):
        logger.debug(
            "Creating AsyncPolyswarmRequest instance.\nRequest parameters: %s\nResult parser: %s",
            request_parameters,
            result_parser.__name__ if result_parser else "No result parser",
        )
        self.api_instance = api_instance
        self.session = self.api_instance.session or PolyswarmSession(
            key, retries=settings.DEFAULT_RETRIES
        )
        self.timeout = self.api_instance.timeout or settings.DEFAULT_HTTP_TIMEOUT
        self.request_parameters = request_parameters
        self.result_parser = result_parser
        self.raw_result = None
        self.status_code = None
        self.status = None
        self.errors = None
        self._result = None

        self._paginated = False
        self.total = None
        self.limit = None
        self.offset = None
        self.order_by = None
        self.direction = None
        self.has_more = None

        self.parser_kwargs = kwargs

    def result(self):
        if self._paginated:
            return self.consume_results()
        else:
            return self._result

    def execute(self):
        logger.debug("Executing request.")
        self.request_parameters.setdefault("timeout", self.timeout)

        params = dict(self.request_parameters)
        method = params.pop("method")
        url = params.pop("url")
        params.pop("stream", None)
        if "headers" in params:
            params["headers"] = {
                k: v for k, v in params["headers"].items() if v is not None
            }
            if not params["headers"]:
                del params["headers"]

        self.raw_result = self.session.request(method, url, **params)
        logger.debug("Request returned code %s", self.raw_result.status_code)

        # Non-JSON parsers expect a ``requests.Response``-shaped object with
        # ``iter_content``. Wrap the ``httpx.Response`` so file downloads etc.
        # see the surface they expect.
        result_for_parsing = self.raw_result
        if (
            self.result_parser
            and not issubclass(self.result_parser, BaseJsonResource)
            and not hasattr(self.raw_result, "iter_content")
        ):
            result_for_parsing = HttpxResponseAdapter(self.raw_result)

        self.parse_result(result_for_parsing)
        return self

    def _bad_status_message(self):
        request_parameters = json.dumps(
            self.request_parameters, indent=4, sort_keys=True, cls=RequestParamsEncoder
        )
        message = (
            f"Error when running the request:\n{request_parameters}\n"
            f"Return code: {self.status_code}\n"
            f"Message: {self._result}"
        )
        if self.errors:
            errors = "\n".join(str(error) for error in self.errors)
            message = f"{message}\nErrors:\n{errors}"
        return message

    def _extract_json_body(self, result):
        self.json = result.json()
        self._result = self.json.get("result")
        self.status = self.json.get("status")
        self.errors = self.json.get("errors")

    def parse_result(self, result):
        self.status_code = result.status_code
        if self.request_parameters["method"] == "HEAD":
            # HEAD: status code IS the result; suppress non-2xx mapping
            # so callers (e.g. ``exists_hash``) can read 404 as "absent"
            # without raising.
            logger.debug(
                "HEAD method does not return results, setting it to the status code."
            )
            self._result = self.status_code
            return
        logger.debug("Parsing request results.")
        try:
            if self.status_code // 100 != 2:
                # Non-2xx: map to the appropriate exception regardless of
                # whether ``result_parser`` is set.
                self._extract_json_body(result)
                if self.status_code == 429:
                    message = (
                        f"{self._result} This may mean you need to purchase a "
                        "larger package, or that you have exceeded "
                        "rate limits. If you continue to have issues, "
                        "please contact us at info@polyswarm.io."
                    )
                    raise exceptions.UsageLimitsExceededException(self, message)
                elif self.status_code == 404:
                    raise exceptions.NotFoundException(self, self._result)
                elif self.status_code == 422:
                    raise exceptions.FailedInstanceException(self, self._result)
                else:
                    raise exceptions.RequestException(self, self._bad_status_message())
            if not self.result_parser:
                # 2xx without a parser: body is intentionally discarded
                # (e.g. fire-and-forget endpoints like ``Webhook.test``).
                logger.debug("Result parser is not defined, skipping parsing results.")
                return
            if self.status_code == 204:
                raise exceptions.NoResultsException(
                    self, "The request returned no results."
                )
            if issubclass(self.result_parser, BaseJsonResource):
                self._extract_json_body(result)
                if (
                    self.request_parameters["method"] == "GET"
                    and "has_more" in self.json
                ):
                    self._paginated = True
                self.total = self.json.get("total")
                self.limit = self.json.get("limit")
                self.offset = self.json.get("offset")
                self.order_by = self.json.get("order_by")
                self.direction = self.json.get("direction")
                self.has_more = self.json.get("has_more")
                if "result" in self.json:
                    result = self.json["result"]
                elif "results" in self.json:
                    result = self.json["results"]
                else:
                    raise exceptions.RequestException(
                        self,
                        'The response standard must contain either the "result" or "results" key.',
                    )
                if isinstance(result, list):
                    self._result = self.result_parser.parse_result_list(
                        self.api_instance, result, **self.parser_kwargs
                    )
                else:
                    self._result = self.result_parser.parse_result(
                        self.api_instance, result, **self.parser_kwargs
                    )
            else:
                self._result = self.result_parser.parse_result(
                    self.api_instance, result, **self.parser_kwargs
                )
        except JSONDecodeError as e:
            if self.status_code == 404:
                raise exceptions.NotFoundException(
                    self, "The requested endpoint does not exist."
                ) from e
            else:
                err_msg = (
                    f"Server returned non-JSON response [{self.status_code}]: {result}"
                )
                raise exceptions.RequestException(self, err_msg) from e

    def __iter__(self):
        return self.consume_results()

    def consume_results(self):
        request = self
        while True:
            try:
                for result in request._result:
                    yield result
            except TypeError:
                yield request._result
                return

            if not request.has_more:
                return
            request = request.next_page()

    def next_page(self):
        new_parameters = deepcopy(self.request_parameters)
        params = new_parameters.setdefault("params", {})
        if isinstance(params, dict):
            params["offset"] = self.offset
            params["limit"] = self.limit
        else:
            params = [p for p in params if p[0] != "offset" and p[0] != "limit"]
            params.extend([("offset", self.offset), ("limit", self.limit)])
            new_parameters["params"] = params
        return PolyswarmRequest(
            self.api_instance,
            new_parameters,
            result_parser=self.result_parser,
        ).execute()
