# DO NOT EDIT — generated by scripts/regenerate_sync.py from
# the canonical async source in polyswarm_api/aio/.
# Edit aio/<file>.py then rerun the script.
"""HTTP transport — the session.

The async source lives here; the sync mirror at
``polyswarm_api.session`` is generated by
``scripts/regenerate_sync.py``. Edit only the async file.

The session is the **only** place HTTP I/O happens in this SDK. It
owns an ``httpx.AsyncClient`` and exposes three coroutine methods:

- ``execute(request)`` — the authenticated round-trip. Sends the
  ``PolyswarmRequest`` descriptor, attaches the raw response,
  delegates to ``parse_response`` for body interpretation, and
  returns the now-populated request. Typed HTTP exceptions raised
  by ``parse_response`` already carry ``.request = request`` (set in
  the exception constructor) — the session re-raises them as-is.
- ``upload_file(url, artifact, …)`` — PUT a file to a pre-signed URL
  with the session-level ``Authorization`` header stripped (so the
  PolySwarm API key doesn't leak to S3). Retries on transient errors.
- ``upload_logo(url, file, content_type, …)`` — companion to
  ``upload_file`` for the report-template logo endpoint, with
  ``Content-Type`` set on the PUT.

Customization is via subclass + inject: override any of the three
methods on a subclass and pass it as ``session=`` to the api client.
See ``specs/05-downstream-contract.md`` for the contract.
"""

import io
import logging

import httpx

from polyswarm_api import exceptions, settings  # noqa: F401  (exceptions re-exported by callers)
from polyswarm_api.core import (
    BaseJsonResource,
    HttpxResponseAdapter,
    parse_response,
)

logger = logging.getLogger(__name__)


class PolyswarmSession:
    """The async transport. Owns one ``httpx.AsyncClient`` and exposes
    every HTTP-I/O operation the SDK performs.
    """

    def __init__(
        self,
        key,
        retries=settings.DEFAULT_RETRIES,
        user_agent=settings.DEFAULT_USER_AGENT,
        verify=True,
        timeout=settings.DEFAULT_HTTP_TIMEOUT,
        **httpx_kwargs,
    ):
        logger.debug("Creating %s (httpx-backed)", type(self).__name__)
        self.verify = verify
        hdrs = httpx_kwargs.pop("headers", None) or {}
        if key:
            hdrs["Authorization"] = key
        if user_agent:
            hdrs["User-Agent"] = user_agent
        transport = httpx_kwargs.pop("transport", None) or httpx.HTTPTransport(
            retries=retries,
            verify=verify,
        )
        self._client = httpx.Client(
            headers=hdrs,
            transport=transport,
            timeout=timeout,
            verify=verify,
            follow_redirects=True,
            **httpx_kwargs,
        )

    # ── Authenticated round-trip ──────────────────────────────────

    def execute(self, request):
        """Send ``request`` and parse the response.

        Pure delegation of request-projection / I/O / response-parsing
        to the dataclass + ``parse_response``. The session is the
        single place ``await`` and the httpx client meet.
        """
        kwargs = request.to_httpx_kwargs()
        suppress = request.suppressed_headers()

        if suppress:
            # Caller asked to drop session-level headers (e.g.
            # ``Authorization`` for a pre-signed S3 download). Build the
            # request via ``build_request`` so the client/request header
            # merge happens, then pop the suppressed names.
            req = self._client.build_request(request.method, request.url, **kwargs)
            for header_name in suppress:
                req.headers.pop(header_name, None)
            response = self._client.send(req)
        else:
            response = self._client.request(request.method, request.url, **kwargs)

        logger.debug("Request returned code %s", response.status_code)

        # Non-JSON parsers expect a ``requests.Response``-shaped object
        # with ``iter_content``. Wrap the ``httpx.Response`` so file
        # downloads etc. see the surface they expect.
        response_for_parsing = response
        if (
            request.result_parser
            and not issubclass(request.result_parser, BaseJsonResource)
            and not hasattr(response, "iter_content")
        ):
            response_for_parsing = HttpxResponseAdapter(response)

        parse_response(response_for_parsing, request)
        return request

    # ── Pre-signed-URL uploads ────────────────────────────────────

    def upload_file(self, upload_url, artifact, attempts=3, **kwargs):
        """PUT ``artifact`` to a pre-signed URL.

        The session-level ``Authorization`` header is stripped from the
        outgoing PUT — pre-signed URLs carry their own auth in the
        query parameters and the PolySwarm API key must not leak to
        the object store.

        Retries up to ``attempts`` times on transient HTTP / transport
        errors. Re-raises the last exception when retries are
        exhausted.
        """
        if not upload_url:
            raise exceptions.InvalidValueException(
                "upload_url must be set to upload a file",
            )
        if not artifact:
            raise exceptions.InvalidValueException(
                "A LocalArtifact must be provided in order to upload",
            )

        last_exc = None
        for attempt_no in range(attempts):
            artifact.seek(0, io.SEEK_END)
            length = artifact.tell()
            artifact.seek(0)
            # Empty files use empty bytes to avoid chunked encoding.
            data = b"" if not length else artifact.read()
            try:
                r = self._put_off_domain(upload_url, content=data, **kwargs)
                r.raise_for_status()
                return r
            except (httpx.HTTPStatusError, httpx.TransportError) as e:
                last_exc = e
                logger.debug(
                    "upload attempt %d/%d failed: %r",
                    attempt_no + 1,
                    attempts,
                    e,
                )
        raise last_exc

    def upload_logo(self, upload_url, logo_file, content_type, attempts=3, **kwargs):
        """PUT ``logo_file`` to a pre-signed URL with ``Content-Type`` set.

        Same auth-strip + retry semantics as :meth:`upload_file`. The
        ``Content-Type`` header carries the image MIME type.
        """
        if not upload_url:
            raise exceptions.InvalidValueException(
                "upload_url must be set to upload a file",
            )

        headers = dict(kwargs.pop("headers", None) or {})
        headers["Content-Type"] = content_type

        last_exc = None
        for attempt_no in range(attempts):
            logo_file.seek(0, io.SEEK_END)
            length = logo_file.tell()
            logo_file.seek(0)
            data = b"" if not length else logo_file.read()
            try:
                r = self._put_off_domain(
                    upload_url,
                    content=data,
                    headers=headers,
                    **kwargs,
                )
                r.raise_for_status()
                return r
            except (httpx.HTTPStatusError, httpx.TransportError) as e:
                last_exc = e
                logger.debug(
                    "logo upload attempt %d/%d failed: %r",
                    attempt_no + 1,
                    attempts,
                    e,
                )
        raise last_exc

    def _put_off_domain(self, url, *, content, headers=None, **kwargs):
        """PUT ``content`` to ``url`` with the session-level
        ``Authorization`` header stripped.

        Shared helper for the two upload paths. ``client.put`` merges
        client + request headers and won't honour ``None`` as
        suppression; we go through ``client.build_request`` (which
        performs the merge) and pop the header off the resulting
        ``Headers`` before ``client.send``.

        Override on a subclass to change off-domain auth handling
        (e.g. inject S3 SigV4, swap the credential).
        """
        req_headers = dict(headers) if headers else {}
        req = self._client.build_request(
            "PUT",
            url,
            content=content,
            headers=req_headers,
            **kwargs,
        )
        req.headers.pop("Authorization", None)
        return self._client.send(req)

    # ── Lifecycle ─────────────────────────────────────────────────

    @property
    def headers(self):
        return self._client.headers

    def close(self):
        self._client.close()
