# DO NOT EDIT — generated by scripts/regenerate_sync.py from
# the canonical async source in polyswarm_api/aio/.
# Edit aio/<file>.py then rerun the script.
"""S3 upload for PolySwarm artifact submission.

Module-level callable so downstream consumers can monkey-patch the
upload path. See specs/05-downstream-contract.md.
"""

import io
import logging

import httpx

from polyswarm_api import exceptions

logger = logging.getLogger(__name__)


def upload_file(
    client: httpx.Client,
    upload_url: str,
    artifact,
    attempts: int = 3,
    **kwargs,
) -> httpx.Response:
    """Upload a file to a pre-signed S3 URL.

    Args:
        client: the httpx client owned by the corresponding session
            (``httpx.AsyncClient`` in this async source; the generated
            sync mirror takes ``httpx.Client``).
        upload_url: pre-signed S3 URL from the API response.
        artifact: file-like object to upload.
        attempts: number of retry attempts.
        **kwargs: forwarded to ``client.put`` (e.g. ``headers``,
            ``timeout``). Downstream callers and monkey-patches that
            previously passed extra kwargs to ``requests.put`` continue
            to work; kwargs honoured by ``httpx`` are honoured here.
    """
    if not upload_url:
        raise exceptions.InvalidValueException(
            "upload_url must be set to upload a file"
        )
    if not artifact:
        raise exceptions.InvalidValueException(
            "A LocalArtifact must be provided in order to upload"
        )

    r = None
    while attempts > 0 and not r:
        attempts -= 1
        artifact.seek(0, io.SEEK_END)
        length = artifact.tell()
        artifact.seek(0)
        # Empty files use empty bytes to avoid chunked encoding.
        if not length:
            data = b""
        else:
            data = artifact.read()
        r = client.put(upload_url, content=data, **kwargs)
        r.raise_for_status()
    return r


def upload_logo(
    client: httpx.Client,
    upload_url: str,
    logo_file,
    content_type: str,
    **kwargs,
) -> httpx.Response:
    """Upload a logo image for a report template.

    Companion to ``async_upload_file`` for the report-template logo
    endpoint, where the request body is the image bytes and the
    ``Content-Type`` header carries the MIME type. Kept as a module-
    level callable for the same monkey-patch reasons that
    ``async_upload_file`` is — see ``specs/05-downstream-contract.md``.

    Args:
        client: the httpx client owned by the corresponding session.
        upload_url: pre-signed URL the logo should be PUT to.
        logo_file: file-like (read into bytes before sending).
        content_type: value for the ``Content-Type`` header on the PUT.
        **kwargs: forwarded to ``client.put`` (e.g. ``timeout``).
    """
    if not upload_url:
        raise exceptions.InvalidValueException(
            "upload_url must be set to upload a file"
        )

    logo_file.seek(0, io.SEEK_END)
    length = logo_file.tell()
    logo_file.seek(0)
    if not length:
        data = b""
    else:
        data = logo_file.read()

    headers = kwargs.pop("headers", None) or {}
    headers["Content-Type"] = content_type

    r = client.put(upload_url, content=data, headers=headers, **kwargs)
    r.raise_for_status()
    return r
