# DO NOT EDIT — generated by scripts/regenerate_sync.py from
# the canonical async source in polyswarm_api/aio/.
# Edit aio/<file>.py then rerun the script.
"""S3 upload for PolySwarm artifact submission.

Module-level callable so downstream consumers can monkey-patch the
upload path. See specs/05-downstream-contract.md.
"""

import io
import logging

import httpx

from polyswarm_api import exceptions

logger = logging.getLogger(__name__)


def _put_without_session_auth(
    client: httpx.Client,
    url: str,
    *,
    content,
    headers=None,
    **kwargs,
) -> httpx.Response:
    """PUT to ``url`` via ``client`` with the client's session-level
    ``Authorization`` header stripped.

    Pre-signed S3 URLs carry their own auth in the query parameters;
    shipping the PolySwarm API key as ``Authorization`` would leak it
    to S3. ``client.put`` merges client + request headers and doesn't
    honour ``None`` as suppression, so we go through
    ``client.build_request`` and pop the header off the resulting
    ``Headers`` before ``client.send``.
    """
    req_headers = dict(headers) if headers else {}
    req = client.build_request(
        "PUT", url, content=content, headers=req_headers, **kwargs
    )
    req.headers.pop("Authorization", None)
    return client.send(req)


def upload_file(
    client: httpx.Client,
    upload_url: str,
    artifact,
    attempts: int = 3,
    **kwargs,
) -> httpx.Response:
    """Upload a file to a pre-signed S3 URL.

    The session-level ``Authorization`` header (the PolySwarm API key)
    is stripped from the outgoing PUT — pre-signed URLs handle auth via
    the query parameters and we don't want to leak the API key to the
    object store.

    Args:
        client: the httpx client owned by the corresponding session
            (``httpx.AsyncClient`` in this async source; the generated
            sync mirror takes ``httpx.Client``).
        upload_url: pre-signed S3 URL from the API response.
        artifact: file-like object to upload.
        attempts: number of retry attempts on transient HTTP errors.
        **kwargs: forwarded to ``client.put`` (e.g. ``headers``,
            ``timeout``).
    """
    if not upload_url:
        raise exceptions.InvalidValueException(
            "upload_url must be set to upload a file"
        )
    if not artifact:
        raise exceptions.InvalidValueException(
            "A LocalArtifact must be provided in order to upload"
        )

    last_exc = None
    for attempt_no in range(attempts):
        artifact.seek(0, io.SEEK_END)
        length = artifact.tell()
        artifact.seek(0)
        # Empty files use empty bytes to avoid chunked encoding.
        data = b"" if not length else artifact.read()
        try:
            r = _put_without_session_auth(
                client,
                upload_url,
                content=data,
                **kwargs,
            )
            r.raise_for_status()
            return r
        except (httpx.HTTPStatusError, httpx.TransportError) as e:
            last_exc = e
            logger.debug(
                "upload attempt %d/%d failed: %r",
                attempt_no + 1,
                attempts,
                e,
            )
    # Exhausted retries — re-raise the last error so callers see it.
    raise last_exc


def upload_logo(
    client: httpx.Client,
    upload_url: str,
    logo_file,
    content_type: str,
    attempts: int = 3,
    **kwargs,
) -> httpx.Response:
    """Upload a logo image for a report template.

    Companion to ``async_upload_file`` for the report-template logo
    endpoint, where the request body is the image bytes and the
    ``Content-Type`` header carries the MIME type. Kept as a module-
    level callable for the same monkey-patch reasons that
    ``async_upload_file`` is — see ``specs/05-downstream-contract.md``.

    As with ``async_upload_file``, the session-level ``Authorization``
    header is suppressed on the outbound request.

    Args:
        client: the httpx client owned by the corresponding session.
        upload_url: pre-signed URL the logo should be PUT to.
        logo_file: file-like (read into bytes before sending).
        content_type: value for the ``Content-Type`` header on the PUT.
        attempts: number of retry attempts on transient HTTP errors.
        **kwargs: forwarded to ``client.put`` (e.g. ``timeout``).
    """
    if not upload_url:
        raise exceptions.InvalidValueException(
            "upload_url must be set to upload a file"
        )

    headers = kwargs.pop("headers", None) or {}
    headers = dict(headers)
    headers["Content-Type"] = content_type

    last_exc = None
    for attempt_no in range(attempts):
        logo_file.seek(0, io.SEEK_END)
        length = logo_file.tell()
        logo_file.seek(0)
        data = b"" if not length else logo_file.read()
        try:
            r = _put_without_session_auth(
                client,
                upload_url,
                content=data,
                headers=headers,
                **kwargs,
            )
            r.raise_for_status()
            return r
        except (httpx.HTTPStatusError, httpx.TransportError) as e:
            last_exc = e
            logger.debug(
                "logo upload attempt %d/%d failed: %r",
                attempt_no + 1,
                attempts,
                e,
            )
    raise last_exc
